var templates = [
        'templates/layout/header.html',
        'templates/layout/footer.html',
        'assets/css/app.css',
        'assets/css/reset.css',
        'assets/css/public.css',
        'assets/css/animate.css',
        'assets/css/fonts.css',
        'assets/css/media.css',
        'mockData/login.json',
        'components/legalSelector/index.html',
        'components/legalSelector/style.css',
        'components/legalSelector/index.js',
        'config/app-api.js',
        'config/app-env.js',
        'config/config-local.js',
        'config/config-dev.js',
        'config/config-stg.js',
        'config/config-prd.js',
        'modules/model.js',
        'modules/view.js',
        'assets/images/loading.gif',
        'assets/fonts/icomoon.eot',
        'assets/fonts/icomoon.svg',
        'assets/fonts/icomoon.ttf',
        'assets/fonts/icomoon.woff',
        'views/index.html',
        'views/login.html',
        'modules/passport/loginView.js',
        'assets/js/SYST/SYST.js',
        'assets/js/SYST/SYST.min.js',
        'assets/js/plugins/fastclick.js',
        'gupack-config.js'
    ];

module.exports = templates;